### PR TITLE
fix: calculate `skipTest` when test name available

### PR DESCRIPTION
**Pull request by owlcode**

### CODE REVIEW

**Review by ValentinH — APPROVED** [review]

**Comment by owlcode** [comment]
@ValentinH Is there anything more you need from me to approve workflow, merge & release?

**Comment by ValentinH** [comment]
No sorry, I was just waiting to be on my computer to merge and release it 😊

**Comment by ValentinH** [comment]
I really need to take the time to setup an automatic release action 😅

**Comment by ValentinH** [comment]
Released as https://github.com/ValentinH/jest-fail-on-console/releases/tag/v3.0.2

**Comment by ValentinH** [comment]
Thanks for the contribution @owlcode  🎉

**Comment by owlcode** [comment]
Thanks for your time 👍

**Pull request merged**
